@HotelBooking_HostAddress = https://localhost:7065

POST {{HotelBooking_HostAddress}}/rooms
Content-Type: application/json

{
  "number": 46,
  "type": "standard",
  "capacity": 3,
  "price": 70
}

###

PUT {{HotelBooking_HostAddress}}/rooms/1
Content-Type: application/json

{
  "number": 254,
  "type": "lux",
  "capacity":5,
  "price": 450
}

###

DELETE {{HotelBooking_HostAddress}}/rooms/1

###

POST {{HotelBooking_HostAddress}}/bookings
Content-Type: application/json

{
  "guestName": "Tom",
  "checkIn": "2026-10-01",
  "checkOut": "2026-10-05",
  "paymentMethod": "card",
  "roomId": 2
}

###

PUT {{HotelBooking_HostAddress}}/bookings/5
Content-Type: application/json

{
  "guestName": "Anna",
  "checkIn": "2026-10-03",
  "checkOut": "2026-10-07",
  "paymentMethod": "cash",
  "roomId": 2
}

###

DELETE {{HotelBooking_HostAddress}}/bookings/1
