@HotelBooking_HostAddress = https://localhost:7065

POST {{HotelBooking_HostAddress}}/rooms
Content-Type: application/json

{
  "number": 101,
  "type": "standard",
  "capacity": 2,
  "price": 50
}

###

PUT {{HotelBooking_HostAddress}}/rooms/2
Content-Type: application/json

{
  "number": 254,
  "type": "lux",
  "capacity":5,
  "price": 450
}